### ISSUE TITLE
fix for 3.0 compat

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_FXOS8700#2]
this line https://github.com/adafruit/Adafruit_CircuitPython_FXOS8700/blob/master/adafruit_fxos8700.py#L34

should be
```
try:
    import ustruct as struct
except:
    import struct
```

and then change all uses of 'ustruct' to 'struct' for 3.0 compatibility!

**Comment by dhalbert** [comment]
Fixed by #4.
